### PR TITLE
[atc_api] Properly set context for index page

### LINKED ISSUE #204: Index not working since
since https://github.com/facebook/augmented-traffic-control/commit/2af41120eb199c57537195c85eb9c72a690a643d the index page stopped working failing with something like https://gist.github.com/chantra/3ad0d1eb7bbd6703cd79

The issue is that `GetClientAddr` now needs to be able to access the server from the request context.
In the case of the rootHandler, we were not setting the context causing the crash..

### PR DESCRIPTION
**Pull request by chantra**
Fixes #204

Accessing the index page was failing with error below.
Fixes the error and add unittest:
https://gist.github.com/chantra/78c4dba2cbf972974e72

goroutine 25 [running]:
net/http.(_conn).serve.func1(0xc8201493f0, 0x7f0ff586ba10, 0xc820024468)
    /usr/local/go/src/net/http/server.go:1287 +0xb5
github.com/facebook/augmented-traffic-control/src/api.getProxiedClientAddr(0x0,
0xc8203a4a80, 0x0, 0x0, 0x0, 0x0)
    /usr/src/myapp/.gopath/src/github.com/facebook/augmented-traffic-control/src/api/utils.go:156
+0x7b1
github.com/facebook/augmented-traffic-control/src/api.GetClientAddr(0xc8203a4a80,
0x0, 0x0)
    /usr/src/myapp/.gopath/src/github.com/facebook/augmented-traffic-control/src/api/utils.go:151
+0x61
github.com/facebook/augmented-traffic-control/src/api.bindInfo.getPrimarySecondaryAddrs(0x9ecec8,
0x7, 0x7fff73955e72, 0xe, 0x0, 0x0, 0xc82000ff00, 0x4, 0xc8203a4a80,
0x0, ...)
    /usr/src/myapp/.gopath/src/github.com/facebook/augmented-traffic-control/src/api/assets.go:20
+0x50
github.com/facebook/augmented-traffic-control/src/api.(_bindInfo).templateFor(0xc8200109c0,
0xc8203a4a80, 0x833)
    /usr/src/myapp/.gopath/src/github.com/facebook/augmented-traffic-control/src/api/assets.go:56
+0xb4
github.com/facebook/augmented-traffic-control/src/api.rootHandler.func1(0x7f0ff586c1b0,
0xc8201494a0, 0xc8203a4a80)
    /usr/src/myapp/.gopath/src/github.com/facebook/augmented-traffic-control/src/api/assets.go:83
+0x676
net/http.HandlerFunc.ServeHTTP(0xc820138ad0, 0x7f0ff586c1b0,
0xc8201494a0, 0xc8203a4a80)
    /usr/local/go/src/net/http/server.go:1422 +0x3a
github.com/gorilla/mux.(_Router).ServeHTTP(0xc820014a00, 0x7f0ff586c1b0,
0xc8201494a0, 0xc8203a4a80)
    /usr/src/myapp/.gopath/src/github.com/gorilla/mux/mux.go:100 +0x29e
net/http.serverHandler.ServeHTTP(0xc82013a540, 0x7f0ff586c1b0,
0xc8201494a0, 0xc8203a4a80)
    /usr/local/go/src/net/http/server.go:1862 +0x19e
net/http.(_conn).serve(0xc8201493f0)
    /usr/local/go/src/net/http/server.go:1361 +0xbee
created by net/http.(*Server).Serve
    /usr/local/go/src/net/http/server.go:1910 +0x3f6

### CODE REVIEW

File: src/api/api_test.go [hunk 1]
```diff
@@ -28,6 +28,19 @@ var ServerAddr = net.IPv4zero
...
+	defer srv.Cleanup()
+	cli := srv.client(Addr1)
+
+	resp := cli.GetIndex()
+
+	if resp.StatusCode != 200 {
+		t.Error("Wrong status code:", resp.StatusCode)
+	}
+}
+
```
Comment (zfjagann) [inline src/api/api_test.go]: Yes!

**Comment by zfjagann** [comment]
Awesome! After having played around with golang templates for a while I decided we should try to avoid them. They don't offer strong typing and can't be checked at compile time easily. We're not using them extensively, so I think switching to the `/info` endpoint is pretty easy and useful.
